name: Publish Package to npmjs

on:
  release:
    types: [published]
  workflow_run:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with: { run_install: false }

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.14"
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - run: pnpm build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          # see https://github.com/pnpm/pnpm/issues/6435#issuecomment-1518397267
          NPM_CONFIG_PROVENANCE: "true"
